name: haze
version: 0.1.0.0
github: complyue/haze
license: BSD3
author: Compl Yue
maintainer: compl.yue@icloud.com
copyright: 2019 Compl Yue

extra-source-files:
  - README.md

data-files:
  - web/**/*

synopsis: interactive Haskell stack project with Bokeh plotting
category: Visualization

description: Please see the README on Github at <https://github.com/complyue/haze>

dependencies:
  - base
  - rio

  - hadui

  - containers
  - aeson
  - aeson-qq

ghc-options:
  - -Wall

library:
  source-dirs: src
